import type {Metadata} from 'next';
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'EbaAaZ - Firebase Studio App',
  description: 'Generated by Firebase Studio',
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="header">
          <div className="header-menu">
            <Link href="/" style={{ margin: '0 10px' }}>Home</Link>
            <Link href="/github-mcp-server" style={{ margin: '0 10px' }}>GitHub MCP Server</Link>
          </div>
        </header>
        {children}
        <footer className="footer">
          <p>&copy; 2025 EbaAaZ</p>
        </footer>
      </body>
    </html>
  );
}

