import type {Metadata} from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Mayfair+Sans:ital,wght@1,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body style={{ fontFamily: 'Mayfair Sans, sans-serif' }}>
        {children}
      </body>
    </html>
  );
}

