import type {Metadata} from 'next';
import {Source_Sans_Pro} from "next/font/google";
import './globals.css';

const sourceSansPro = Source_Sans_Pro({
  variable: '--font-source-sans-pro',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourceSansPro.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

